set_location_assignment PIN_E1 -to Clk50M
set_location_assignment PIN_M16 -to Rst_n
set_location_assignment PIN_M9 -to Sd_Ba[1]
set_location_assignment PIN_T12 -to Sd_Ba[0]
set_location_assignment PIN_R11 -to Sd_Cas_n
set_location_assignment PIN_T11 -to Sd_Cke
set_location_assignment PIN_T10 -to Sd_Clk
set_location_assignment PIN_R12 -to Sd_Cs_n
set_location_assignment PIN_P9 -to Sd_Dq[15]
set_location_assignment PIN_N8 -to Sd_Dq[14]
set_location_assignment PIN_M8 -to Sd_Dq[13]
set_location_assignment PIN_L8 -to Sd_Dq[12]
set_location_assignment PIN_K8 -to Sd_Dq[11]
set_location_assignment PIN_L9 -to Sd_Dq[10]
set_location_assignment PIN_K9 -to Sd_Dq[9]
set_location_assignment PIN_R9 -to Sd_Dq[8]
set_location_assignment PIN_R8 -to Sd_Dq[7]
set_location_assignment PIN_R6 -to Sd_Dq[6]
set_location_assignment PIN_T5 -to Sd_Dq[5]
set_location_assignment PIN_R5 -to Sd_Dq[4]
set_location_assignment PIN_T4 -to Sd_Dq[3]
set_location_assignment PIN_R4 -to Sd_Dq[2]
set_location_assignment PIN_T3 -to Sd_Dq[1]
set_location_assignment PIN_R3 -to Sd_Dq[0]
set_location_assignment PIN_R10 -to Sd_Dqm[1]
set_location_assignment PIN_T8 -to Sd_Dqm[0]
set_location_assignment PIN_N9 -to Sd_Ras_n
set_location_assignment PIN_N11 -to Sd_Sa[12]
set_location_assignment PIN_R13 -to Sd_Sa[11]
set_location_assignment PIN_M10 -to Sd_Sa[10]
set_location_assignment PIN_T14 -to Sd_Sa[9]
set_location_assignment PIN_R14 -to Sd_Sa[8]
set_location_assignment PIN_T15 -to Sd_Sa[7]
set_location_assignment PIN_L11 -to Sd_Sa[6]
set_location_assignment PIN_M11 -to Sd_Sa[5]
set_location_assignment PIN_N12 -to Sd_Sa[4]
set_location_assignment PIN_T13 -to Sd_Sa[3]
set_location_assignment PIN_P14 -to Sd_Sa[2]
set_location_assignment PIN_L10 -to Sd_Sa[1]
set_location_assignment PIN_P11 -to Sd_Sa[0]
set_location_assignment PIN_T9 -to Sd_We_n
set_location_assignment PIN_J15 -to TFT_clk
set_location_assignment PIN_J11 -to TFT_de
set_location_assignment PIN_K11 -to TFT_hs
set_location_assignment PIN_J12 -to TFT_pwm
set_location_assignment PIN_P16 -to TFT_rgb[15]
set_location_assignment PIN_N15 -to TFT_rgb[14]
set_location_assignment PIN_R16 -to TFT_rgb[13]
set_location_assignment PIN_P15 -to TFT_rgb[12]
set_location_assignment PIN_N13 -to TFT_rgb[11]
set_location_assignment PIN_L12 -to TFT_rgb[10]
set_location_assignment PIN_K12 -to TFT_rgb[9]
set_location_assignment PIN_L13 -to TFT_rgb[8]
set_location_assignment PIN_M12 -to TFT_rgb[7]
set_location_assignment PIN_L14 -to TFT_rgb[6]
set_location_assignment PIN_N16 -to TFT_rgb[5]
set_location_assignment PIN_J16 -to TFT_rgb[4]
set_location_assignment PIN_K15 -to TFT_rgb[3]
set_location_assignment PIN_K16 -to TFT_rgb[2]
set_location_assignment PIN_J13 -to TFT_rgb[1]
set_location_assignment PIN_L15 -to TFT_rgb[0]
set_location_assignment PIN_J14 -to TFT_vs
set_location_assignment PIN_B5 -to Uart_rx