@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jan 06 14:38:20 +0800 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_yt3817_BPPU_behav -key {Behavioral:sim_1:Functional:tb_yt3817_BPPU} -tclbatch tb_yt3817_BPPU.tcl -view D:/Temp_desktop/EDA_design/project/yt3817_fig/yt3817_digit_detect_sim/tb_yt3817_BPPU_behav.wcfg -log simulate.log"
call xsim  tb_yt3817_BPPU_behav -key {Behavioral:sim_1:Functional:tb_yt3817_BPPU} -tclbatch tb_yt3817_BPPU.tcl -view D:/Temp_desktop/EDA_design/project/yt3817_fig/yt3817_digit_detect_sim/tb_yt3817_BPPU_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
